# Generated by Django 6.0.3 on 2026-04-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=20, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('channel', models.CharField(max_length=100)),
                ('sender_id', models.CharField(db_index=True, max_length=20)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_role', models.CharField(max_length=100)),
                ('message_text', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('normal', 'Normal'), ('risk_indicator', 'Risk Indicator')], db_index=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
