# Generated by Django 6.0.3 on 2026-04-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_alter_message_options_message_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_role',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
