# Generated by Django 6.0.3 on 2026-04-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0004_alter_message_sender_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadbatch',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='error_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='failed_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
