# Generated by Django 6.0.3 on 2026-04-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messages_app', '0004_alter_message_sender_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged', models.BooleanField(db_index=True, default=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('method', models.CharField(choices=[('rule_based', 'Rule Based'), ('tfidf', 'TF-IDF'), ('hybrid', 'Hybrid')], default='rule_based', max_length=20)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_results', to='messages_app.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
