# Generated by Django 6.0.3 on 2026-04-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0001_initial'),
        ('messages_app', '0005_alter_uploadbatch_options_uploadbatch_error_log_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='auditresult',
            constraint=models.UniqueConstraint(fields=('message', 'method'), name='unique_audit_message_result'),
        ),
    ]
