# Generated by Django 6.0.3 on 2026-05-21 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0004_auditsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditresult',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='audit_app.auditsession'),
        ),
    ]
