# Generated by Django 6.0.3 on 2026-05-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0007_auditsession_closed_at_auditsession_closed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditsession',
            name='closed_by',
        ),
    ]
